### ISSUE TITLE
Error trying to generate file on Atom 0.204.0 (Fedora 22)

### ISSUE THREAD

**Issue by jeqo** [mrohland/plantuml#4]
Hi,

I receive an error message: "ReferenceError: path is not defined" when I tried to generate PlantUML file.

To fix it I add 

```
path = require('path')
```

To the file: lib/file-utils.coffee, and it works. 

If you can add it to update the package would be great.

**Comment by mrohland** [comment]
Thx. I already opened an issue for this: #2 . Therefor I'm closing this, plan is to release a fixed version over the weekend.
